import { PhilosopherProfile, PhilosopherWork } from "./types";

/**
 * Profile-page content for each philosopher: hero portrait, an accessible
 * 5–7 sentence introduction, and 3–5 major works.
 *
 * Book covers are generated by <BookCover> from this bibliographic data and
 * the philosopher's accent colour. No third-party cover image is stored or
 * fetched by a profile.
 */

export const PROFILES: PhilosopherProfile[] = [
  {
    id: "aquinas",
    shortName: "Aquinas",
    heroImage: "/philosophers/heroes/aquinas.webp",
    heroFocus: "50% 12%",
    intro: [
      "Thomas Aquinas was a Dominican friar, philosopher, and theologian who became one of the most important intellectual figures of the thirteenth century. He studied and taught in the developing European university system, particularly at the University of Paris. During this period, Western scholars were gaining access to a much larger collection of Aristotle’s writings, many of which had been preserved and interpreted by Muslim and Jewish philosophers. These works offered a comprehensive philosophical account of nature, human beings, ethics, and reality, but some Aristotelian ideas appeared to conflict with Christian teachings about creation, divine providence, and the immortality of the individual soul.",
      "Aquinas became the leading figure in the effort to reconcile Aristotle’s philosophy with Christian theology. He did not accept Aristotle uncritically, but adopted and modified concepts such as act and potency, matter and form, causation, virtue, and the natural purposes of living things. Aquinas argued that faith and reason cannot truly contradict one another because both ultimately come from God. Philosophers outside Christianity, including Aristotle, could therefore discover genuine truths through observation and rational argument. However, Aquinas also maintained that certain truths—such as the Trinity, the Incarnation, and humanity’s supernatural union with God—could be known only through divine revelation.",
      "From this synthesis came Aquinas’s Five Ways, which use features of the observable world such as motion, causation, contingency, degrees of perfection, and natural order to argue for the existence of God. He also developed a moral philosophy grounded in natural law, according to which human reason can recognize basic moral principles by understanding human nature and its proper ends. His Summa Theologiae brought these philosophical and theological ideas together into a systematic account of God, creation, morality, law, grace, and human fulfillment. Aquinas’s synthesis of Aristotelian philosophy and Christian theology remains foundational to Catholic thought and continues to influence debates in metaphysics, ethics, natural law, and the philosophy of religion.",
    ],
    works: [
      {
        title: "Summa Theologiae",
        year: "1265–1274",
        description:
          "Aquinas's vast summary of theology, organized as thousands of disputed questions, objections, and replies. It moves from God and creation through human action and virtue to Christ, containing the Five Ways and the treatise on natural law. Unfinished at his death, it remains the central work of scholastic philosophy.",
      },
      {
        title: "Summa contra Gentiles",
        year: "1259–1265",
        description:
          "A four-book defense of Christian wisdom addressed to those who do not accept Scripture's authority, and so argued as far as possible from reason alone. It treats God's existence and nature, creation, providence, and the end of human life. It is Aquinas's most sustained exercise in purely philosophical argument.",
      },
      {
        title: "On Being and Essence",
        year: "c. 1252–1256",
        description:
          "A short early treatise on what things are and what it means for them to exist. Here Aquinas draws his famous distinction between essence and existence — identical only in God — laying the metaphysical foundation for everything that follows.",
      },
    ],
  },
  {
    id: "nietzsche",
    shortName: "Nietzsche",
    heroImage: "/philosophers/heroes/nietzsche.webp",
    heroFocus: "50% 14%",
    intro: [
      "Friedrich Nietzsche was a German philosopher and classical philologist (the study of language, literature, and historical texts) who became one of the most influential critics of Western religion, morality, and culture. Nietzsche specialized in the literature and culture of ancient Greece and Rome and became a professor of classical philology at the University of Basel at only twenty-four years old. Persistent health problems eventually forced him to resign, after which he spent much of his life traveling through Switzerland, Italy, and France and writing independently.",
      "Nietzsche believed that European civilization was entering a crisis caused by the decline of Christianity and its traditional moral authority. He expressed this through the declaration that “God is dead,” which did not simply mean that he personally rejected belief in God. It meant that Christian explanations of reality and morality were losing their power over European society, while no new system of values had yet replaced them. Nietzsche warned that this collapse could lead to nihilism: the belief that life has no objective meaning, purpose, or value.",
      "In response, Nietzsche called for a “revaluation of all values.” He examined how moral ideas developed historically and argued that many traditional values arose from weakness, resentment, and hostility toward human strength and excellence. Rather than passively inheriting these values, individuals should critically examine them and develop life-affirming values of their own. His ideas of the will to power, the Übermensch, and eternal recurrence explored self-overcoming, the creation of values, and the challenge of affirming life even with its suffering. Nietzsche’s critique of Christianity, morality, truth, and modern culture strongly influenced existentialism, psychology, literary theory, and later continental philosophy.",
    ],
    works: [
      {
        title: "Thus Spoke Zarathustra",
        year: "1883–1885",
        description:
          "A philosophical prose-poem in which the prophet Zarathustra descends from his mountain to teach the Übermensch and the meaning of the earth. It contains Nietzsche's most famous images — the last man, the tightrope walker, eternal recurrence. He considered it his deepest and most personal book.",
      },
      {
        title: "Beyond Good and Evil",
        year: "1886",
        description:
          "A sweeping critique of past philosophers for mistaking their prejudices for truths, and a \"prelude to a philosophy of the future.\" It develops perspectivism, the will to power, and the contrast between master and slave morality in taut, dangerous aphorisms.",
      },
      {
        title: "On the Genealogy of Morality",
        year: "1887",
        description:
          "Three connected essays tracing where our moral concepts actually come from: the slave revolt that inverted \"good and bad\" into \"good and evil,\" the origins of guilt and bad conscience, and the meaning of ascetic ideals. It is Nietzsche's most systematic and most influential book.",
      },
      {
        title: "The Gay Science",
        year: "1882",
        description:
          "Aphorisms on knowledge, art, and the joyful discipline of thinking, written in convalescent high spirits. It announces the death of God through the parable of the madman, and poses eternal recurrence as a test: could you affirm your life if it repeated forever?",
      },
    ],
  },
  {
    id: "kierkegaard",
    shortName: "Kierkegaard",
    heroImage: "/philosophers/heroes/kierkegaard.webp",
    heroFocus: "50% 20%",
    intro: [
      "Søren Kierkegaard spent most of his life in Copenhagen, where he studied theology and became a sharp critic of the intellectual and religious culture of nineteenth-century Denmark. He wrote in opposition to the influence of G. W. F. Hegel, whose philosophical system sought to explain reality, history, and human development through a comprehensive rational framework. Kierkegaard believed that this approach overlooked the concrete individual who must make choices and live through uncertainty rather than merely understand existence in abstract terms.",
      "He therefore turned philosophy inward, focusing on the individual’s subjective experience of anxiety, despair, freedom, faith, and personal responsibility. Against Christian Hegelianism and the established Danish Church, he argued that Christianity was not simply a set of doctrines that could be rationally understood or inherited through membership in society. It required a passionate personal commitment that had to be lived despite uncertainty. Through pseudonymous works presenting different ways of life—the aesthetic, the ethical, and the religious—Kierkegaard explored how a person becomes a self and develops an authentic relationship with God. Because of this emphasis on individual existence, choice, and lived experience, he is widely regarded as the Father of Existentialism.",
    ],
    works: [
      {
        title: "Either/Or",
        year: "1843",
        description:
          "A sprawling double volume contrasting two ways of life: the aesthete's pursuit of mood and possibility, and the judge's defense of marriage, choice, and commitment. Between the seducer's diary and the ethicist's letters, the reader is forced to confront the book's title as a personal question.",
      },
      {
        title: "Fear and Trembling",
        year: "1843",
        description:
          "A meditation on Abraham, commanded to sacrifice his son, written under the pseudonym Johannes de Silentio. It asks whether there can be a \"teleological suspension of the ethical\" and what faith costs the one who has it. Its portrait of the knight of faith remains existentialism's founding image.",
      },
      {
        title: "The Concept of Anxiety",
        year: "1844",
        description:
          "A dense psychological study of anxiety as \"the dizziness of freedom\" — the vertigo that comes with possibility itself. Connecting dread, innocence, and freedom's first stirring, it anticipates modern psychology by half a century.",
      },
      {
        title: "Philosophical Fragments",
        year: "1844",
        description:
          "A short, teasing thought-experiment by Johannes Climacus: could an eternal truth ever be learned in time, or must the teacher bring the condition for learning it with him? Against Socratic recollection it sets the paradox of the god in time, approached not by proof but by faith. It is the book behind Kierkegaard's claim that what matters is the truth a person can live in, not the store of objective facts they hold.",
      },
      {
        title: "The Sickness unto Death",
        year: "1849",
        description:
          "Anti-Climacus's anatomy of despair: the ways a self can fail to be itself, from unconscious drifting to open defiance. Its cure — resting transparently in the power that established the self — is Kierkegaard's most concentrated statement of faith.",
      },
    ],
  },
  {
    id: "sartre",
    shortName: "Sartre",
    heroImage: "/philosophers/heroes/sartre.webp",
    heroFocus: "50% 16%",
    intro: [
      "Jean-Paul Sartre was a French philosopher, novelist, and playwright who became one of the leading intellectual figures of twentieth-century Europe. During World War II, he served in the French Army before being captured by German forces in 1940 and held in a prisoner-of-war camp. While imprisoned, Sartre studied Martin Heidegger’s Being and Time, which greatly influenced the development of his own philosophy. After returning to Paris, he helped form Socialisme et Liberté, a short-lived intellectual group associated with the French Resistance. Building on the phenomenology of Heidegger and Edmund Husserl, Sartre developed an atheistic form of existentialism centered on human freedom.",
      "His most famous claim, “existence precedes essence,” means that human beings are not born with a predetermined nature or purpose. Instead, people define themselves through their choices and actions and are therefore responsible for the lives they create. Sartre explored the difficulty of accepting this freedom and the ways people attempt to escape from it. He called this self-deception “bad faith,” which occurs when individuals treat their identities, circumstances, or social roles as if they completely determine what they must do. He also examined how being observed and judged by others can cause people to see themselves as fixed objects rather than free individuals. Through his philosophical works, novels, and plays, Sartre became the most influential representative of twentieth-century existentialism.",
    ],
    works: [
      {
        title: "Being and Nothingness",
        year: "1943",
        description:
          "Sartre's phenomenological masterwork on consciousness, freedom, and self-deception. Through famous set pieces — the café waiter, the gaze, the woman on a date — it argues that we are \"condemned to be free\" and responsible without excuse. It made existentialism a philosophy.",
      },
      {
        title: "Nausea",
        year: "1938",
        description:
          "A philosophical novel in diary form: Antoine Roquentin discovers the raw, contingent existence of things beneath our tidy labels — and it sickens him. Sartre's central ideas arrive here first, as lived experience rather than argument.",
      },
      {
        title: "No Exit and Three Other Plays",
        year: "1944",
        description:
          "The drama in which three strangers, locked forever in a drawing room, become one another's torturers. Its famous line — \"hell is other people\" — dramatizes Sartre's account of the gaze and being-for-others.",
      },
      {
        title: "Existentialism Is a Humanism",
        year: "1946",
        description:
          "The famous public lecture defending existentialism against its critics: if existence precedes essence, then man is nothing but what he makes of himself. Short, direct, and the best gateway into Sartre's thought.",
      },
    ],
  },
  {
    id: "camus",
    shortName: "Camus",
    heroImage: "/philosophers/heroes/camus.webp",
    heroFocus: "50% 22%",
    intro: [
      "Albert Camus was a French-Algerian novelist, essayist, and playwright who became one of the most influential writers of the twentieth century. He grew up in a working-class family in French Algeria and later moved to France, where he participated in the French Resistance and served as an editor of the underground newspaper Combat during World War II. Although often associated with existentialism, Camus rejected the label and developed his philosophy around what he called the absurd.",
      "For Camus, the absurd arises from the conflict between the human desire for meaning, order, and purpose and an indifferent, godless universe that provides no clear answers. In The Myth of Sisyphus, he argued that the absurd should lead neither to suicide nor to religious or philosophical explanations that impose a false meaning on life. Instead, a person should live with full awareness of the absurd and respond through revolt: the continuing decision to live, act, and create without pretending that life possesses an ultimate purpose.",
      "Camus later extended this idea into political and moral philosophy. In The Rebel, he examined how rebellion against injustice can become destructive when it abandons moral limits and attempts to justify violence in the name of a perfect future. This position contributed to his public disagreement with Jean-Paul Sartre over revolutionary violence and communism. Camus instead emphasized moderation, solidarity, individual dignity, and resistance to injustice.",
      "Camus intended to follow his explorations of the absurd and revolt with a third stage of his work centered on love. However, this final stage was never completed. He died in a car accident in 1960, and the handwritten draft of his unfinished autobiographical novel The First Man was recovered from his satchel at the crash site. The novel, which explores his childhood in Algeria and his love for his mother, was not published until 1994. Because Camus died before completing this work and the broader cycle it was associated with, his final ideas about love remained unfinished.",
    ],
    works: [
      {
        title: "The Myth of Sisyphus",
        year: "1942",
        description:
          "The essay that begins from \"the one truly serious philosophical problem\" — suicide — and builds Camus's account of the absurd. Its answer is revolt without appeal, crowned by the image of Sisyphus, whom we must imagine happy.",
      },
      {
        title: "The Stranger",
        year: "1942",
        description:
          "The novel of Meursault, who kills a man on an Algerian beach and is condemned as much for failing to weep at his mother's funeral. Its flat, sunstruck prose made the absurd a lived atmosphere rather than a thesis.",
      },
      {
        title: "The Plague",
        year: "1947",
        description:
          "A chronicle of a quarantined city, where a doctor fights an epidemic he cannot defeat. At once a realist novel and an allegory of occupied Europe, it stakes out Camus's ethic of solidarity and common decency without metaphysical hope.",
      },
      {
        title: "The Rebel",
        year: "1951",
        description:
          "Camus's study of rebellion from the Greeks to the gulags, asking how revolt against injustice becomes a justification for murder. \"I rebel, therefore we are\" — but rebellion must honor limits. The book cost him his friendship with Sartre.",
      },
    ],
  },
  {
    id: "hume",
    shortName: "Hume",
    heroImage: "/philosophers/heroes/hume.webp",
    heroFocus: "50% 17%",
    intro: [
      "David Hume was a Scottish philosopher, essayist, and historian who wanted to study the human mind as carefully as scientists studied nature. He asked where our beliefs come from, why we trust them, and how we decide what is right or wrong. Hume's answer was that experience shapes far more of our thinking than pure reason does. Our memories, habits, emotions, and relationships all help form what we believe.",
      "Hume pointed out that we never actually see one event causing another. We see the same pattern many times and grow used to expecting it. This does not mean that all beliefs are equally good: reasonable people should match the strength of their beliefs to the strength of the evidence. Hume also thought morality begins in human feelings, especially our ability to care about other people. He explained laws and government as useful arrangements people develop so they can live together. His approach strongly influenced modern thinking about knowledge and science, although his writings also contain troubling views about race, gender, and social class.",
    ],
    works: [
      {
        title: "A Treatise of Human Nature",
        year: "1739–1740",
        description:
          "Hume's ambitious early system of the understanding, passions, and morals. It develops his accounts of impressions and ideas, causal inference, personal identity, motivation, sympathy, and the conventions supporting justice.",
      },
      {
        title: "An Enquiry Concerning Human Understanding",
        year: "1748",
        description:
          "A polished reconstruction of Hume's philosophy of knowledge. Through compact arguments about causation, induction, testimony, miracles, liberty, and skepticism, it asks what human beings may reasonably claim to know.",
      },
      {
        title: "An Enquiry Concerning the Principles of Morals",
        year: "1751",
        description:
          "Hume's mature account of moral judgment, grounded in sentiment but disciplined by facts, consequences, sympathy, and a general point of view. He regarded it as the best of his writings.",
      },
      {
        title: "Dialogues Concerning Natural Religion",
        year: "1779",
        description:
          "A posthumously published dialogue in which Cleanthes, Demea, and Philo test arguments about design, divine attributes, evil, and the limits of analogy. Its dramatic form makes Hume's final position deliberately difficult to reduce to one speaker.",
      },
    ],
  },
  {
    id: "plato",
    shortName: "Plato",
    heroImage: "/philosophers/heroes/plato.webp",
    heroFocus: "50% 15%",
    intro: [
      "Plato was an Athenian philosopher who founded the Academy, one of the earliest schools of higher learning in the Western world. He presented his philosophy through dialogues—written conversations in which Socrates and other characters question one another. Plato never speaks in these works as himself, so readers still debate which ideas belong to him and which ones he wanted his audience to examine rather than accept.",
      "Plato believed that the world we see is always changing, so it cannot give us perfect knowledge by itself. He argued that lasting truths such as Justice, Beauty, and Equality exist as unchanging patterns he called Forms. Particular things are imperfect examples of these Forms. In the famous story of the Cave, people mistake shadows for reality until education turns them toward the truth. Plato also compared a just person with a just society: reason should guide courage and desire, just as wise leaders should guide the city. His later dialogues raise serious problems for the theory of Forms, showing that he treated philosophy as an ongoing search rather than a finished set of answers.",
      "How we come to know anything at all sits at the center of this. The senses, Plato argued, can only report a world that keeps shifting—a thing is beautiful next to one object and ugly next to another, large beside this and small beside that—so what they give us is opinion, not knowledge. Knowledge is reached by turning away from the senses and reasoning: testing definitions in question and answer until the ones that cannot survive are thrown out, and training the mind on mathematics, where the eye is no help whatsoever. In the Meno, Socrates draws a geometrical proof out of a slave boy who was never taught it, which Plato offers as evidence that learning is really recollection—the soul recovering what it already grasped. It is also why the Cave ends as it does: the prisoner is not handed better information, he is turned around and made to walk out. Plato's own student Aristotle rejected exactly this, and insisted that knowledge starts from observing the changing world Plato had set aside.",
    ],
    works: [
      {
        title: "Republic",
        year: "c. 375 BC",
        description:
          "An extended argument about what justice is and whether the just life is better for the person living it. It contains the tripartite soul, the ideal city and its philosopher-rulers, the critique of poetry, and the images of the Sun, the Divided Line, and the Cave.",
      },
      {
        title: "Phaedo",
        year: "c. 380 BC",
        description:
          "Set on the day of Socrates' execution, it presents several arguments for the immortality of the soul, including the theory that learning is recollection. It is the dialogue in which the Forms are most explicitly introduced as separate realities.",
      },
      {
        title: "Symposium",
        year: "c. 385 BC",
        description:
          "A series of speeches on love at a drinking party, ending with Socrates' report of Diotima's teaching that erotic desire, properly educated, ascends from individual beauty to Beauty itself.",
      },
      {
        title: "Parmenides",
        year: "c. 370 BC",
        description:
          "The elderly Parmenides presses a young Socrates with objections to the theory of Forms, including the regress known as the Third Man. Plato records the difficulties without answering them, and the dialogue marks a turn in his later method.",
      },
    ],
  },
  {
    id: "aristotle",
    shortName: "Aristotle",
    heroImage: "/philosophers/heroes/aristotle.webp",
    heroFocus: "50% 15%",
    intro: [
      "Aristotle was the tutor of Alexander the Great and later founded his own school, the Lyceum, in Athens. He studied an enormous range of subjects, including logic, biology, politics, poetry, and ethics. Instead of relying only on abstract ideas, Aristotle closely examined plants, animals, governments, and everyday human behavior. His surviving works read more like teaching notes than finished books, but they created many of the basic terms and methods that philosophers and scientists still use.",
      "Aristotle spent about twenty years at Plato's Academy, and ended up rejecting his teacher's central idea. Plato held that the world we see is an unreliable copy of perfect, unchanging Forms, and that real knowledge is reached by reasoning and looking inward, away from the senses. Aristotle argued close to the opposite. Forms set apart from ordinary things explain nothing about how a real thing grows, moves, or fails; knowledge begins in common experience, in what people already notice about the world, and is built up by observing the particular animal, the particular city, the particular illness in front of you.",
      "That is why Aristotle is often called the first scientist. He did not only argue about nature, he investigated it and recorded what he found: dissecting animals, describing how a chick develops inside its egg, classifying hundreds of species by observed features, and collecting the constitutions of more than a hundred Greek cities to compare them. He insisted that an explanation must name what actually causes a thing and must answer to what is observed, and he invented formal logic to set out how such explanations hold together. Much of his physics and astronomy was later shown to be wrong, but the method—observe, record, classify, explain—is the part science kept.",
      "Aristotle believed we understand a thing by learning what it is made of, what shape or structure it has, what produced it, and what purpose it serves. In ethics, he taught that a good life is built through practice. We become brave, fair, and generous by repeatedly making brave, fair, and generous choices. Virtue usually avoids both too much and too little—for example, courage lies between cowardice and recklessness—but good judgment must fit the situation. Aristotle also believed that people naturally live in communities and compared different forms of government. Some of his political views, especially his defense of slavery and claims about women, were deeply unjust and remain important criticisms of his work.",
    ],
    works: [
      {
        title: "Nicomachean Ethics",
        year: "c. 340 BC",
        description:
          "Aristotle's account of the human good, developed through the function argument, the doctrine of the mean, and extended treatments of practical wisdom, weakness of will, friendship, and pleasure. It remains the founding text of virtue ethics.",
      },
      {
        title: "Metaphysics",
        year: "c. 340 BC",
        description:
          "A collection of studies on being as such, substance, potentiality and actuality, and the first causes of things. It includes his sustained criticism of Plato's Forms and the argument for an unmoved mover.",
      },
      {
        title: "Politics",
        year: "c. 335 BC",
        description:
          "An examination of the city as a natural association aimed at living well, with a comparative survey of constitutions, an analysis of how regimes change and fail, and a proposal for the best practicable state.",
      },
      {
        title: "Physics",
        year: "c. 350 BC",
        description:
          "Aristotle's general theory of nature: change, matter and form, the four causes, place, time, infinity, and motion. It supplies the conceptual framework presupposed by most of his other scientific work.",
      },
    ],
  },
  {
    id: "epicurus",
    shortName: "Epicurus",
    heroImage: "/philosophers/heroes/epicurus.webp",
    heroFocus: "50% 24%",
    intro: [
      "Epicurus taught in a school called the Garden outside Athens. Unlike many schools of his time, his community included women and enslaved people. Epicurus compared philosophy to medicine because he believed its purpose was to heal fear and worry. He wrote hundreds of works, but only a few letters, short sayings, and quotations have survived.",
      "Epicurus taught that everything, including the human soul, is made of tiny particles called atoms. When the body dies, the soul breaks apart, so death cannot be experienced and should not be feared. He also believed the gods do not punish or reward human beings. Epicurus called pleasure the highest good, but he did not mean constant luxury. The best pleasure is a simple life without physical pain or mental distress, supported by friendship and careful choices. Food, shelter, safety, and companionship are easier to satisfy than endless desires for wealth, fame, or power. This is why the popular image of Epicurus as someone devoted to excess is almost the opposite of what he taught.",
    ],
    works: [
      {
        title: "Letter to Menoeceus",
        year: "c. 300 BC",
        description:
          "A short summary of Epicurean ethics addressed to a student, covering the gods, death, the classification of desires, and the role of prudence. It contains the argument that death is nothing to us.",
      },
      {
        title: "Principal Doctrines",
        year: "c. 300 BC",
        description:
          "Forty maxims collecting the core of the system in memorizable form, including the limits of pleasure, the conditions of security, and the account of justice as a compact of mutual advantage.",
      },
      {
        title: "Letter to Herodotus",
        year: "c. 300 BC",
        description:
          "A compressed statement of Epicurean physics: atoms and void, the infinity of the universe, the nature and mortality of the soul, and the method of explaining phenomena without recourse to divine agency.",
      },
      {
        title: "Vatican Sayings",
        year: "c. 300 BC",
        description:
          "A second collection of maxims, rediscovered in the Vatican Library in 1888, overlapping with the Principal Doctrines but adding material on friendship, self-sufficiency, and the management of desire.",
      },
    ],
  },
  {
    id: "marcus-aurelius",
    shortName: "Marcus Aurelius",
    heroImage: "/philosophers/heroes/marcus-aurelius.webp",
    heroFocus: "50% 15%",
    intro: [
      "Marcus Aurelius was a Roman emperor who ruled during years of war, disease, and financial trouble. During this difficult period, he kept a private notebook that later became known as the Meditations. He was writing reminders to himself, not a book for the public. The repeated advice shows a powerful ruler working to control his temper, perform his duties, and live by the Stoic philosophy he admired.",
      "Stoicism taught Marcus to separate what he could control from what he could not. He could not control illness, reputation, bad luck, or other people's behavior, but he could examine his own judgments and choose how to respond. He believed people were made to cooperate and that serving the common good mattered more than wealth, praise, or comfort. His frequent thoughts about death were meant to make each day clearer and more valuable, not gloomy. Marcus did not always live up to these ideals: he ruled an empire, fought wars, and lived in a society built partly on slavery. The Meditations record his effort to become better, not proof that he was perfect.",
    ],
    works: [
      {
        title: "Meditations",
        year: "c. 170–180",
        description:
          "Twelve books of private notes on judgment, duty, mortality, and the discipline of assent. Book I is a catalogue of debts to family and teachers; the rest circles repeatedly over a small set of principles the author was trying to make habitual.",
      },
    ],
  },
  {
    id: "augustine",
    shortName: "Augustine",
    heroImage: "/philosophers/heroes/augustine.webp",
    heroFocus: "50% 22%",
    intro: [
      "Augustine was born in Roman North Africa and became a successful teacher of public speaking before converting to Christianity at age thirty-two. He later became the bishop of Hippo. His most famous book, the Confessions, tells the story of his restless search for truth and examines his own memories, mistakes, desires, and faith. The questions he studied—why evil exists, why people act against their better judgment, and whether the mind can know the truth—were also problems he had faced in his own life.",
      "Augustine argued that evil is not a separate thing fighting against goodness. It is a loss or absence of the good that should be present, like rot in healthy wood. He also believed that the human will is divided: we may know what is right and still not fully want to do it. For Augustine, people need God's freely given help, or grace, to heal this weakness. He explored time by arguing that the past exists for us as memory and the future as expectation, both experienced in the present mind. He also described history as a struggle between communities shaped by selfish love and communities shaped by love of God. These ideas deeply influenced Western Christianity and philosophy.",
    ],
    works: [
      {
        title: "Confessions",
        year: "c. 397–400",
        description:
          "An account of Augustine's life to his conversion, written as a sustained address to God rather than to a reader. The last books turn from narrative to philosophy, treating memory, time, and the interpretation of Genesis.",
      },
      {
        title: "City of God",
        year: "413–426",
        description:
          "Begun after the sack of Rome in 410 as a defence of Christianity against the charge that it had weakened the empire. It develops into a philosophy of history organized around two cities formed by two loves, and includes extensive criticism of Roman religion and philosophy.",
      },
      {
        title: "On Free Choice of the Will",
        year: "c. 388–395",
        description:
          "A dialogue asking how a good God can be the source of a world containing evil, locating the answer in the free movement of the created will. Augustine later judged parts of it too favourable to human capacity and qualified them.",
      },
      {
        title: "On Christian Teaching",
        year: "397–426",
        description:
          "A treatise on signs, meaning, and interpretation, setting out how a text is to be read and how the resources of classical rhetoric may legitimately be used. It shaped medieval theories of language and education.",
      },
    ],
  },
  {
    id: "spinoza",
    shortName: "Spinoza",
    heroImage: "/philosophers/heroes/spinoza.webp",
    heroFocus: "50% 21%",
    intro: [
      "Baruch Spinoza was born into Amsterdam's Portuguese-Jewish community but was expelled from it at age twenty-three for reasons that are not fully recorded. He earned a modest living by grinding lenses and turned down a university job so he could protect his independence. Because his ideas about God and religion were dangerous in his time, he published very little under his own name. His major work, the Ethics, appeared only after his death.",
      "Spinoza argued that God and nature are not separate. They are two names for the one reality that includes everything. Minds, bodies, and events are all parts or expressions of that reality, and everything happens through causes rather than chance or a divine plan. This means we are not free in the sense of making choices without causes. We become freer by understanding the causes of our thoughts, emotions, and actions instead of being pushed around by feelings we do not understand. Spinoza treated emotions as natural events to study, not sins to condemn. He also defended freedom of thought and argued that reading religious texts in their historical setting can support a peaceful society.",
    ],
    works: [
      {
        title: "Ethics",
        year: "1677",
        description:
          "Spinoza's central work, set out in the manner of Euclid with definitions, axioms, and demonstrated propositions. Its five parts move from God and the nature of substance through mind, the emotions, and human bondage to the account of freedom and blessedness.",
      },
      {
        title: "Theological-Political Treatise",
        year: "1670",
        description:
          "Published anonymously and rapidly banned. It argues for the historical-critical reading of Scripture, denies that prophecy yields speculative knowledge, and defends freedom of philosophizing as necessary to the security of the state.",
      },
      {
        title: "Political Treatise",
        year: "1677",
        description:
          "An unfinished work analysing monarchy, aristocracy, and democracy in terms of what actually holds power stable, rather than what an ideal citizen ought to do. It begins from people as they are rather than as philosophers wish them to be.",
      },
      {
        title: "Treatise on the Emendation of the Intellect",
        year: "c. 1662",
        description:
          "An early, unfinished essay on method, opening with the question of what good is genuinely worth pursuing and proceeding to distinguish kinds of knowledge and the conditions of adequate ideas.",
      },
    ],
  },
  {
    id: "james",
    shortName: "James",
    heroImage: "/philosophers/heroes/james.webp",
    heroFocus: "50% 15%",
    intro: [
      "William James trained as a doctor and taught psychology and philosophy at Harvard. His writing helped establish psychology as an experimental science in the United States. He paid close attention to ordinary experience: how thoughts flow, how habits form, how attention works, and how people make difficult choices. Unlike philosophers who tried to fit everything into one grand system, James preferred clear examples and remained open to several possible ways of understanding the world.",
      "James helped develop pragmatism, an approach that asks what real difference an idea makes in practice. If two theories would change nothing about experience or action, he thought their disagreement might be empty. He said an idea proves true when it continues to guide us successfully through experience and fits the evidence—not simply when it is convenient to believe. James described consciousness as a personal and constantly changing stream rather than a row of separate thoughts. He also argued that when an important choice cannot be avoided or settled by evidence, commitment may reasonably help decide it. This was a defense of serious moral and religious choices, not permission to ignore available facts.",
    ],
    works: [
      {
        title: "The Principles of Psychology",
        year: "1890",
        description:
          "A two-volume work, twelve years in the writing, that founded scientific psychology in America. It contains the account of the stream of consciousness, the chapters on habit and the self, and the emotion theory now known as James-Lange.",
      },
      {
        title: "Pragmatism",
        year: "1907",
        description:
          "Eight lectures presenting pragmatism as both a method for settling disputes and a theory of truth, positioned as a middle way between tough-minded empiricism and tender-minded rationalism.",
      },
      {
        title: "The Varieties of Religious Experience",
        year: "1902",
        description:
          "The Gifford Lectures, treating conversion, mysticism, saintliness, and the divided self as psychological data to be examined on their own terms rather than explained away or defended doctrinally.",
      },
      {
        title: "The Will to Believe",
        year: "1897",
        description:
          "A collection of essays defending the legitimacy of belief in advance of evidence where the question is living, forced, and momentous, together with pieces on determinism, rationality, and moral philosophy.",
      },
    ],
  },
  {
    id: "beauvoir",
    shortName: "Beauvoir",
    heroImage: "/philosophers/heroes/beauvoir.webp",
    heroFocus: "50% 36%",
    intro: [
      "Simone de Beauvoir was a French philosopher, novelist, memoir writer, and political activist. She passed France's demanding philosophy teaching exam at age twenty-one and wrote for more than fifty years. Beauvoir worked closely with Jean-Paul Sartre, but she developed important ideas of her own, especially about ethics, women's lives, and the ways society can either support or restrict freedom.",
      "In The Second Sex, Beauvoir argued that men had been treated as the normal model of a human being while women were defined as secondary or different. Her famous claim that one is not born but becomes a woman means that biology alone does not decide a woman's role. Family expectations, education, stories, laws, and economic limits teach people what society thinks women should be. Beauvoir believed freedom requires the chance to choose meaningful goals, but unfair social conditions can block those choices. Because our projects depend on other people, she argued that genuinely valuing our own freedom also requires us to value theirs. Her work helped shape modern feminism, though critics have fairly challenged its limited treatment of race, class, and colonialism.",
    ],
    works: [
      {
        title: "The Second Sex",
        year: "1949",
        description:
          "A two-volume study of how women have been constituted as the Other, drawing on biology, psychoanalysis, historical materialism, myth, and extensive first-person testimony. It is the founding text of modern feminist philosophy.",
      },
      {
        title: "The Ethics of Ambiguity",
        year: "1947",
        description:
          "Beauvoir's attempt to derive an ethics from existentialist premises, arguing that human beings are neither pure freedom nor mere things, and that one's own freedom is realised only in willing the freedom of others.",
      },
      {
        title: "The Coming of Age",
        year: "1970",
        description:
          "A study of old age as a condition constructed and imposed by society rather than a natural fate, examining how cultures treat people once they cease to be economically productive.",
      },
      {
        title: "Memoirs of a Dutiful Daughter",
        year: "1958",
        description:
          "The first volume of her autobiography, tracing her bourgeois Catholic upbringing, her loss of faith, and her intellectual formation. It is also a case study in the process The Second Sex analyses.",
      },
    ],
  },
  {
    id: "foucault",
    shortName: "Foucault",
    heroImage: "/philosophers/heroes/foucault.webp",
    heroFocus: "58% 15%",
    intro: [
      "Michel Foucault was a French thinker who studied the history of prisons, hospitals, mental illness, medicine, and sexuality. He often worked with records such as prison rules, medical reports, and old instruction manuals. Instead of assuming that modern ideas were natural or inevitable, he asked when they appeared, who used them, and how they changed people's lives. He also campaigned publicly on issues involving prisons, psychiatry, and immigration.",
      "Foucault argued that power does more than stop people from acting. Schools, prisons, hospitals, governments, and experts also use schedules, tests, records, and labels to shape behavior and define what counts as normal. These practices produce knowledge about groups such as patients, students, and criminals, while that knowledge makes new forms of control possible. In his history of sexuality, Foucault challenged the idea that modern society simply silenced sex. He argued that people were encouraged to talk about it in ways that made sexuality seem like the hidden truth of who they were. His larger point was that many categories that feel permanent have histories—and could therefore be changed.",
    ],
    works: [
      {
        title: "Discipline and Punish",
        year: "1975",
        description:
          "A history of the shift from public torture to the modern prison, and of the disciplinary techniques that spread from it through the institutions of modern life. It contains the analysis of Bentham's Panopticon as a diagram of power.",
      },
      {
        title: "The History of Sexuality, Volume 1",
        year: "1976",
        description:
          "An attack on the assumption that the modern West repressed sexuality, arguing that it instead multiplied discourse about sex and constituted sexuality as the hidden truth of the subject. It introduces the concept of biopower.",
      },
      {
        title: "The Order of Things",
        year: "1966",
        description:
          "A study of the underlying orders of knowledge governing the Renaissance, classical, and modern periods, tracing the emergence of the human sciences and arguing that 'man' is a recent and possibly temporary object of knowledge.",
      },
      {
        title: "Madness and Civilization",
        year: "1961",
        description:
          "Foucault's doctoral thesis, a history of how madness was separated from reason and confined, and of how the asylum came to be understood as a humane advance rather than a new form of control.",
      },
    ],
  },
  {
    id: "descartes",
    shortName: "Descartes",
    heroImage: "/philosophers/heroes/descartes.webp",
    heroFocus: "50% 18%",
    intro: [
      "René Descartes was a French philosopher, mathematician, and scientist who helped begin modern philosophy. He worried that many accepted beliefs came from habit or tradition rather than good reasons. To find a firm foundation for knowledge, he used methodical doubt: he temporarily set aside every belief that could possibly be mistaken and looked for something he could not doubt.",
      "Descartes found one certainty: if he was doubting, then he had to exist as a thinking being. This insight became famous as “I think, therefore I am.” He then tried to rebuild knowledge by arguing that God exists and would not systematically deceive us about ideas we understand clearly. Descartes believed the thinking mind and the physical body were fundamentally different, a view called mind-body dualism. That raised a difficult question: if mind and body are different kinds of things, how can they affect each other? Princess Elisabeth of Bohemia pressed him on this problem. Descartes also made major contributions to geometry and optics, even though many parts of his science were later rejected.",
    ],
    works: [
      {
        title: "Discourse on the Method",
        year: "1637",
        description:
          "An intellectual autobiography setting out four rules of method, a provisional morality, the cogito, and samples of Descartes's scientific program. It presents his path as an example rather than a scholastic textbook.",
      },
      {
        title: "Meditations on First Philosophy",
        year: "1641",
        description:
          "Six staged meditations that move through radical doubt to the certainty of thought, arguments for God, the criterion of clear and distinct perception, and the distinction and union of mind and body.",
      },
      {
        title: "Principles of Philosophy",
        year: "1644",
        description:
          "A systematic, numbered presentation of Cartesian metaphysics and natural philosophy intended for teaching. It joins foundational claims about knowledge to an ambitious mechanical account of the physical universe.",
      },
      {
        title: "The Passions of the Soul",
        year: "1649",
        description:
          "Descartes's final book, written in the context of his correspondence with Princess Elisabeth. It treats emotions as natural bodily responses and asks how understanding, habit, judgment, and generosity can regulate them.",
      },
    ],
  },
  {
    id: "locke",
    shortName: "Locke",
    heroImage: "/philosophers/heroes/locke.webp",
    heroFocus: "50% 15%",
    intro: [
      "John Locke was an English physician, political adviser, and philosopher who lived through civil war, religious conflict, exile, and major changes in government. These events made him suspicious of rulers who claimed unlimited authority and thinkers who claimed more certainty than the evidence allowed. Locke wanted to explain what human beings can truly know and how they should make reasonable decisions when certainty is impossible.",
      "Locke argued that the mind does not begin life filled with built-in ideas. Experience supplies the raw material, and the mind combines and compares it to form more complex thoughts. He also said that personal identity depends on the continuity of consciousness and memory rather than simply having the same body or soul. In politics, Locke defended natural rights to life, liberty, and property. Government is legitimate only through the people's consent, and citizens may resist a ruler who violates their rights. These ideas strongly influenced modern democracy. However, Locke excluded some people from religious toleration and had financial and administrative ties to colonialism and slavery, which sharply conflict with his language of freedom and equality.",
    ],
    works: [
      {
        title: "An Essay Concerning Human Understanding",
        year: "1689",
        description:
          "A four-book investigation of the origin and composition of ideas, the nature of language and personal identity, and the scope and limits of knowledge. It is a founding text of British empiricism.",
      },
      {
        title: "Two Treatises of Government",
        year: "1689",
        description:
          "The first treatise attacks patriarchal divine-right monarchy; the second develops natural equality, property, consent, political trust, and a right of resistance when government betrays its purpose.",
      },
      {
        title: "A Letter Concerning Toleration",
        year: "1689",
        description:
          "An argument that civil force cannot produce sincere belief and that churches should be voluntary associations. Its defense of toleration is powerful but stops short of equal protection for every group.",
      },
      {
        title: "Some Thoughts Concerning Education",
        year: "1693",
        description:
          "Practical advice on forming judgment, character, health, and useful habits through experience rather than rote display. The book applies Locke's psychology to education, though chiefly for boys of the propertied class.",
      },
    ],
  },
  {
    id: "kant",
    shortName: "Kant",
    heroImage: "/philosophers/heroes/kant.webp",
    heroFocus: "45% 15%",
    intro: [
      "Immanuel Kant spent almost his entire life in the Prussian city of Königsberg, yet he tried to answer some of philosophy's largest questions. What can human beings know? What makes an action right? What may we reasonably hope for? Kant was especially concerned with a puzzle raised by David Hume: experience shows us what has happened, but how can it give us necessary laws that must always hold?",
      "Kant argued that the mind does not simply copy the world. It actively organizes experience through basic patterns such as space, time, and cause and effect. This lets us gain reliable knowledge of the world as we experience it, but not of reality exactly as it may exist apart from our way of knowing. In ethics, Kant said a moral person follows principles that everyone could follow, not just rules that serve personal desires. His most famous command is to treat every person as an end with their own worth, never merely as a tool. This defense of human dignity became deeply influential, but it conflicts sharply with racist, sexist, and colonial claims Kant made elsewhere in his work.",
    ],
    works: [
      {
        title: "Critique of Pure Reason",
        year: "1781/1787",
        description:
          "Kant's account of how a priori forms and concepts make experience possible, why mathematics and natural science can be objectively valid, and why theoretical reason generates illusions when it reaches beyond possible experience.",
      },
      {
        title: "Groundwork of the Metaphysics of Morals",
        year: "1785",
        description:
          "A compact search for morality's supreme principle. It develops the good will, action from duty, the formulations of the categorical imperative, autonomy, and the kingdom of ends.",
      },
      {
        title: "Critique of Practical Reason",
        year: "1788",
        description:
          "Kant's mature treatment of moral reason, freedom, respect for the law, and the postulates of God and immortality. It argues that practical reason has authority where theoretical knowledge reaches its limit.",
      },
      {
        title: "Critique of Judgment",
        year: "1790",
        description:
          "An inquiry into judgments of beauty and sublimity and into the purposive organization of living things. It tries to bridge the domains of nature and freedom established by the first two Critiques.",
      },
    ],
  },
  {
    id: "hegel",
    shortName: "Hegel",
    heroImage: "/philosophers/heroes/hegel.webp",
    heroFocus: "50% 14%",
    intro: [
      "G. W. F. Hegel was a German philosopher who came of age during the French Revolution, when old political and religious authorities were being challenged. He believed philosophy had to explain how human thought and society change over time. Ideas are not fixed forever: people discover conflicts within their beliefs, struggle with those conflicts, and develop broader views that preserve what was useful while correcting what failed.",
      "Hegel called this pattern dialectical development, but it is not the simple formula of thesis, antithesis, and synthesis often linked to him. A way of thinking is tested by its own claims and pushed forward when those claims conflict. Hegel also argued that people need recognition from one another to develop a full sense of self. Freedom therefore means more than making private choices; it depends on social institutions such as families, laws, workplaces, and government. His account of history influenced Marxism, existentialism, and many later movements. At the same time, his picture of Europe as the high point of history and his strong support for the state remain major sources of criticism.",
    ],
    works: [
      {
        title: "Phenomenology of Spirit",
        year: "1807",
        description:
          "A dramatic education of consciousness through successive claims to knowledge and freedom. It includes the analyses of sense-certainty, lordship and bondage, unhappy consciousness, reason, ethical life, religion, and absolute knowing.",
      },
      {
        title: "Science of Logic",
        year: "1812–1816",
        description:
          "Hegel's examination of the basic categories of thought and reality as they generate and transform one another. It moves from being through essence to the concept without relying on external examples as its engine.",
      },
      {
        title: "Encyclopaedia of the Philosophical Sciences",
        year: "1817–1830",
        description:
          "A compressed presentation of Hegel's whole system: logic, philosophy of nature, and philosophy of spirit. The successive editions and lecture additions made it the principal framework for his teaching.",
      },
      {
        title: "Elements of the Philosophy of Right",
        year: "1821",
        description:
          "An account of free will becoming concrete through property, morality, family, civil society, and political institutions. Its claims about poverty, corporations, monarchy, and the rational state remain heavily contested.",
      },
    ],
  },
  {
    id: "mill",
    shortName: "Mill",
    heroImage: "/philosophers/heroes/mill.webp",
    heroFocus: "45% 15%",
    intro: [
      "John Stuart Mill received an intense education from early childhood because his father wanted to train him to become a great reformer. After suffering a serious mental crisis in his twenties, Mill came to value emotion, imagination, and individuality as well as reason. He worked for the East India Company, served in Parliament, and campaigned for women's right to vote. Harriet Taylor Mill was his closest intellectual partner and strongly influenced his thinking, though scholars still debate exactly how much of their work was shared.",
      "Mill defended utilitarianism, the view that actions and institutions should be judged by how much happiness and suffering they produce. He argued that happiness is not just a total number of pleasant feelings: learning, friendship, creativity, and the use of our higher abilities can improve the quality of a life. In On Liberty, he said adults should be free to think, speak, and live as they choose unless they harm other people. Free discussion matters because even false ideas can force true beliefs to be tested and understood. Mill also made a powerful case for women's equality. However, his liberal principles sit uneasily beside paternalistic and imperial assumptions in parts of his work.",
    ],
    works: [
      {
        title: "A System of Logic",
        year: "1843",
        description:
          "A large study of inference, induction, explanation, and the methods of the moral and social sciences. It established Mill's philosophical reputation and systematized methods later associated with causal inquiry.",
      },
      {
        title: "Principles of Political Economy",
        year: "1848",
        description:
          "A major synthesis of classical economics with extensive discussions of institutions, distribution, worker cooperatives, population, taxation, and the possibility of a stationary economy.",
      },
      {
        title: "On Liberty",
        year: "1859",
        description:
          "Mill's defense of freedom of thought, discussion, association, and self-directed experiments in living. It formulates the harm principle and warns against social as well as governmental tyranny.",
      },
      {
        title: "Utilitarianism",
        year: "1861",
        description:
          "A concise defense of the greatest-happiness principle, qualitative differences among pleasures, moral motivation, justice, and rights. It distinguishes Mill's utilitarianism from simpler hedonistic calculation.",
      },
      {
        title: "The Subjection of Women",
        year: "1869",
        description:
          "An argument that women's legal and social inequality is unjust and blocks human improvement. Mill attacks appeals to natural sex difference as conclusions drawn from conditions designed to prevent a fair test.",
      },
    ],
  },
  {
    id: "marx",
    shortName: "Marx",
    heroImage: "/philosophers/heroes/marx.webp",
    heroFocus: "50% 15%",
    intro: [
      "Karl Marx studied philosophy, worked as a radical newspaper writer, and spent much of his adult life in exile. With his friend and collaborator Friedrich Engels, he joined revolutionary movements and studied how capitalism works. Marx argued that economic systems are created by people in particular periods of history, even when they seem natural or permanent. He focused on a society in which a small group owns the factories, tools, and resources while most people must sell their ability to work for wages.",
      "Marx argued that workers can be legally free yet still be exploited because they produce more value than they receive in pay. He used the word alienation for the way work can become separated from a worker's creativity, control, community, and sense of purpose. He also believed markets can hide the human relationships behind products, making value seem like a property of objects instead of the result of people's labor. Marx thought these problems could not be solved by individual kindness alone; they required workers to change the economic system together. He did not leave a detailed plan for a communist society, and later governments claimed very different meanings from his work. His writings also contain Eurocentric assumptions that deserve criticism.",
    ],
    works: [
      {
        title: "Economic and Philosophic Manuscripts of 1844",
        year: "1844",
        description:
          "Unpublished notes combining political economy with a philosophical account of alienated labor, private property, human capacities, and communism. Their humanist vocabulary became central to twentieth-century interpretations of Marx.",
      },
      {
        title: "The German Ideology",
        year: "1845–1846",
        description:
          "A sprawling manuscript written with Engels that attacks post-Hegelian philosophy and sketches a materialist approach beginning from real people, productive activity, social relations, and historically formed consciousness.",
      },
      {
        title: "The Communist Manifesto",
        year: "1848",
        description:
          "A short political intervention with Engels describing capitalism's revolutionary transformation of the world, the polarization of class relations, and a program for organized communist struggle.",
      },
      {
        title: "Capital, Volume I",
        year: "1867",
        description:
          "Marx's principal published work of political economy, moving from commodities and money through labor-power, surplus value, machinery, accumulation, and the historical creation of a wage-dependent working class.",
      },
    ],
  },
  {
    id: "heidegger",
    shortName: "Heidegger",
    heroImage: "/philosophers/heroes/heidegger.webp",
    heroFocus: "50% 28%",
    intro: [
      "Martin Heidegger was a German philosopher who asked a basic question he thought earlier thinkers had neglected: what does it mean for anything to be? In Being and Time, he began with ordinary human life rather than a mind cut off from the outside world. We usually meet things as parts of activities—a hammer is something used to build, a classroom is somewhere we learn—before we step back and study them as objects.",
      "Heidegger argued that human life is shaped by care. We enter a world and history we did not choose, but we still choose among possibilities for our future. Most of the time, we follow the anonymous expectations of what “people” normally do. Anxiety and an honest awareness of death can reveal that our time is limited and help us take greater ownership of our lives. In later work, Heidegger warned that modern technology can train us to view nature and even people mainly as resources to control and use. He joined the Nazi Party, promoted the regime as a university rector, expressed antisemitic ideas, and never adequately accounted for these actions. That history is essential to any responsible reading of his philosophy.",
    ],
    works: [
      {
        title: "Being and Time",
        year: "1927",
        description:
          "Heidegger's unfinished masterwork analyzing being-in-the-world, equipment, being-with others, mood, understanding, care, anxiety, death, conscience, authenticity, history, and temporality.",
      },
      {
        title: "Kant and the Problem of Metaphysics",
        year: "1929",
        description:
          "A controversial interpretation of Kant that makes finite imagination central to the possibility of metaphysics. It also clarifies how Heidegger understood his own project immediately after Being and Time.",
      },
      {
        title: "The Origin of the Work of Art",
        year: "1935–1936",
        description:
          "An essay arguing that great art is not merely an object with aesthetic properties but an event in which a world of meaning is opened and the usual concealment of beings is disrupted.",
      },
      {
        title: "The Question Concerning Technology",
        year: "1954",
        description:
          "Heidegger's analysis of modern technology as enframing, a mode of disclosure that orders beings as standing reserve. The essay seeks a freer relation to technology rather than simple rejection of devices.",
      },
    ],
  },
  {
    id: "wittgenstein",
    shortName: "Wittgenstein",
    heroImage: "/philosophers/heroes/wittgenstein.webp",
    heroFocus: "50% 17%",
    intro: [
      "Ludwig Wittgenstein was born into a wealthy family in Vienna, studied engineering, and later turned to logic and philosophy at Cambridge. His thinking changed so greatly that scholars often speak of an early and a later Wittgenstein. In his early book, the Tractatus, he tried to explain how meaningful sentences can picture possible facts about the world. He also argued that questions about ethics and life's deepest meaning cannot be stated in the same factual language used by science.",
      "Years later, Wittgenstein criticized his earlier search for one logical structure behind all language. He began to compare words with tools: the meaning of a word comes from how people use it in a particular activity and way of life. Giving an order, telling a joke, reporting an experiment, and expressing pain follow different kinds of rules. Many philosophical puzzles begin when words are pulled away from their ordinary uses or when one kind of language is mistaken for another. Wittgenstein therefore treated philosophy as a form of therapy. Its job is not always to build a theory, but to untangle confusion by looking carefully at what people actually say and do.",
    ],
    works: [
      {
        title: "Tractatus Logico-Philosophicus",
        year: "1921",
        description:
          "Seven numbered propositions and their remarks on world, fact, picture, proposition, logic, science, value, and the limits of language. Its crystalline structure is both an argument and an exercise in elucidation.",
      },
      {
        title: "Philosophical Investigations",
        year: "1953",
        description:
          "A posthumous sequence of remarks on language-games, family resemblance, rule-following, private language, understanding, sensation, and philosophical method. It is the central text of Wittgenstein's later philosophy.",
      },
      {
        title: "The Blue and Brown Books",
        year: "1933–1935",
        description:
          "Dictated notes for students that document the transition toward the later method. Their concrete examples introduce language-games and examine meaning, explanation, intention, and first-person psychological language.",
      },
      {
        title: "On Certainty",
        year: "1950–1951",
        description:
          "Late remarks prompted by G. E. Moore on doubt, knowledge, evidence, and the untested certainties that form the practical background of inquiry. The notes were written during the final eighteen months of Wittgenstein's life.",
      },
    ],
  },
];

/**
 * Profiles reached from editorial stories without adding those philosophers
 * to the main Explore carousel.
 */
export const CONTEXTUAL_PROFILES: PhilosopherProfile[] = [
  {
    id: "girard",
    shortName: "Girard",
    intro: [
      "René Girard was a French historian, literary critic, and social theorist whose work joined literature, anthropology, religion, and philosophy. His central claim is that human desire is often mimetic: we learn what to want by observing what others want. A model of desire can therefore become a rival, and rivalry can intensify until the original object matters less than defeating the other person.",
      "Girard argued that communities caught in spreading reciprocal conflict can restore temporary order by converging against a single victim. The victim is expelled or killed, and the restored peace makes that victim appear both guilty of the crisis and powerful enough to end it. Girard called this the scapegoat mechanism. He later argued that myths usually conceal this collective violence, while biblical texts increasingly disclose the innocence of the victim. His theory is ambitious and controversial, but it remains influential in literary studies, anthropology, theology, psychology, and accounts of modern competition.",
    ],
    works: [
      {
        title: "Deceit, Desire and the Novel",
        year: "1961",
        description:
          "Girard develops the triangular structure of desire through Cervantes, Stendhal, Flaubert, Proust, and Dostoevsky: a subject learns to desire an object through a model or mediator.",
      },
      {
        title: "Violence and the Sacred",
        year: "1972",
        description:
          "An anthropological account of how mimetic rivalry can spread through a community and how sacrifice redirects reciprocal violence toward a selected victim.",
      },
      {
        title: "Things Hidden Since the Foundation of the World",
        year: "1978",
        description:
          "A wide-ranging dialogue that connects mimetic desire, the scapegoat mechanism, myth, ritual, and Girard's interpretation of biblical revelation.",
      },
      {
        title: "I See Satan Fall Like Lightning",
        year: "1999",
        description:
          "Girard's concise mature presentation of mimetic theory and his argument that biblical texts expose collective persecution from the victim's perspective.",
      },
    ],
  },
];

export const ALL_PROFILES: PhilosopherProfile[] = [
  ...PROFILES,
  ...CONTEXTUAL_PROFILES,
];

export const PROFILE_BY_ID: Record<string, PhilosopherProfile> =
  Object.fromEntries(ALL_PROFILES.map((p) => [p.id, p]));

export function getProfile(id: string): PhilosopherProfile | undefined {
  return PROFILE_BY_ID[id];
}

/**
 * URL-safe identifier for a work, derived from its title so the works data
 * doesn't need a hand-maintained slug field: "Thus Spoke Zarathustra" →
 * "thus-spoke-zarathustra". Used by the "Explore this work" links
 * (/conversation/[id]?work=<slug>) and re-resolved on both ends. Titles are
 * plain ASCII; any non-alphanumeric run collapses to a single hyphen.
 */
export function workSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Resolve a work by its slug within one philosopher's profile. */
export function getWorkBySlug(
  philosopherId: string,
  slug: string,
): PhilosopherWork | undefined {
  return getProfile(philosopherId)?.works.find((w) => workSlug(w.title) === slug);
}
