/**
 * Generates one human-review checklist per philosopher from the draft corpus:
 *   - data/rag/cards/drafts/<p>.md      (position cards)
 *   - data/rag/indexes/<p>.md           (works index)
 *   - data/rag/quotes/drafts/<p>.json   (quote candidates + misattributions)
 *
 * Output: data/rag/review/<p>.md — checkbox per item, with the claim and
 * provenance inline so the reviewer only needs this file plus a browser.
 * Regenerate any time drafts change: npx tsx scripts/build-review-queue.ts
 * (Check marks in existing review files are NOT preserved on regeneration —
 * flip the Status field in the draft itself when something passes review.)
 */
import fs from "node:fs";
import path from "node:path";

const PHILOSOPHERS = ["aquinas", "nietzsche", "kierkegaard", "sartre", "camus"];
const OUT_DIR = path.join("data", "rag", "review");

interface Card {
  section: string;
  title: string;
  claim: string;
  provenance: string;
  status: string;
}

function parseCards(md: string): Card[] {
  const cards: Card[] = [];
  let section = "";
  const lines = md.split(/\r?\n/);
  let cur: Card | null = null;
  let capture: "claim" | null = null;

  for (const line of lines) {
    const h2 = line.match(/^## (.+)$/);
    if (h2) {
      section = h2[1].trim();
      continue;
    }
    const h3 = line.match(/^### (.+)$/);
    if (h3) {
      if (cur) cards.push(cur);
      cur = { section, title: h3[1].trim(), claim: "", provenance: "", status: "" };
      capture = null;
      continue;
    }
    if (!cur) continue;
    if (/^\*\*Claim:?\*\*/.test(line)) {
      capture = "claim";
      const inline = line.replace(/^\*\*Claim:?\*\*:?\s*/, "").trim();
      if (inline) cur.claim = inline;
      continue;
    }
    if (/^\*\*Provenance:?\*\*/.test(line)) {
      capture = null;
      cur.provenance = line.replace(/^\*\*Provenance:?\*\*:?\s*/, "").trim();
      continue;
    }
    if (/^\*\*Status:?\*\*/.test(line)) {
      capture = null;
      cur.status = line.replace(/^\*\*Status:?\*\*:?\s*/, "").trim();
      continue;
    }
    if (/^\*\*/.test(line)) {
      // Any other bold field (Explanation, Citations, Misreadings…) ends claim capture.
      capture = null;
      continue;
    }
    if (capture === "claim" && line.trim() && !cur.claim) {
      cur.claim = line.trim();
    }
  }
  if (cur) cards.push(cur);
  return cards;
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const totals: Record<string, { cards: number; quotes: number }> = {};

  for (const p of PHILOSOPHERS) {
    const cardsPath = path.join("data", "rag", "cards", "drafts", `${p}.md`);
    const indexPath = path.join("data", "rag", "indexes", `${p}.md`);
    const quotesPath = path.join("data", "rag", "quotes", "drafts", `${p}.json`);

    const out: string[] = [];
    const title = p.charAt(0).toUpperCase() + p.slice(1);
    out.push(`# Review queue — ${title}`);
    out.push("");
    out.push(
      "Generated by `scripts/build-review-queue.ts` — do not hand-edit item text",
      "here; fix the draft file instead and regenerate. When an item passes",
      "review, tick it here AND flip its `Status`/`verification` field in the",
      "draft (the draft field is the durable record; ticks are lost on regeneration)."
    );
    out.push("");

    // Works index — one skim item.
    if (fs.existsSync(indexPath)) {
      out.push("## Works index (skim: dates, completeness, one-line accuracy)");
      out.push("");
      out.push(`- [ ] \`${indexPath.replace(/\\/g, "/")}\` reviewed`);
      out.push("");
    }

    // Position cards.
    if (fs.existsSync(cardsPath)) {
      const cards = parseCards(fs.readFileSync(cardsPath, "utf8"));
      totals[p] = { cards: cards.length, quotes: 0 };
      out.push(
        `## Position cards (${cards.length}) — verify claim against provenance source`
      );
      out.push("");
      let lastSection = "";
      for (const c of cards) {
        if (c.section !== lastSection) {
          out.push(`### ${c.section || "(no section)"}`);
          out.push("");
          lastSection = c.section;
        }
        const status = c.status && c.status !== "draft" ? ` _(status: ${c.status})_` : "";
        out.push(`- [ ] **${c.title}**${status}`);
        if (c.claim) out.push(`      — ${c.claim}`);
        if (c.provenance) out.push(`      — _Source:_ ${c.provenance}`);
      }
      out.push("");
    }

    // Quotes.
    if (fs.existsSync(quotesPath)) {
      const q = JSON.parse(fs.readFileSync(quotesPath, "utf8"));
      totals[p].quotes = q.quotes.length;
      out.push(
        `## Quote candidates (${q.quotes.length}) — confirm wording AND citation`
      );
      out.push("");
      for (const item of q.quotes) {
        const flag = item.verification?.startsWith("verified")
          ? " ✅ _machine-verified vs ingested text_"
          : "";
        out.push(`- [ ] "${item.quote}"${flag}`);
        out.push(`      — ${item.work} · ${item.citation}`);
        if (item.note) out.push(`      — _Note:_ ${item.note}`);
      }
      out.push("");
      const warn = [...(q.disputed ?? []), ...(q.misattributions ?? [])];
      if (warn.length) {
        out.push(
          `## Misattribution / disputed entries (${warn.length}) — lighter check: is the debunking explanation itself right?`
        );
        out.push("");
        for (const item of warn) {
          out.push(`- [ ] "${item.quote}"`);
          out.push(`      — ${item.explanation}`);
        }
        out.push("");
      }
    }

    const outPath = path.join(OUT_DIR, `${p}.md`);
    fs.writeFileSync(outPath, out.join("\n"));
    console.log(
      `${outPath}: ${totals[p]?.cards ?? 0} cards, ${totals[p]?.quotes ?? 0} quotes`
    );
  }
}

main();
